### ISSUE TITLE
Multiple ways to encode true, false...

### ISSUE THREAD

**Issue by laurencelundblade** [cbor-wg/CBORbis#1]
This text or similar should be added to section 2.3 on simple values.

It us explicitly forbidden to encode true as 0xf8, 0x14, false as 0xf8 0x1...  The two byte encodings of 0xf8 00 ... 0xf8 1f are forbidden in CBOR and a CBOR decoder MUST treat them as an error.

The encodings of unassigned simple values available to extend CBOR are:
  0… 19 which must be encoded as e0 … f3
  32 … 255 which must be encoded as f8 20 … f8 ff

There was an email exchange between me and Carsten on the list back in early November.

**Comment by paulehoffman** [comment]
Fixed in https://github.com/cbor-wg/CBORbis/pull/7
