### ISSUE TITLE
Map key equivalence

### ISSUE THREAD

**Issue by ii8** [cbor-wg/CBORbis#10]
Is a tagged data item equivalent to the same data item without the tag if used as a key in a map?
The answer to this question is not obvious to me(considering that tags may be completely ignored by decoders) and I cannot find anything explicit in the standard.

A similar question about maps as keys for maps: does the order of keys affect equivalence? Here I would strongly suggest that it does not but this should probably be made explicit as well.

Sorry if this is stated somewhere, I couldn't find it.

**Comment by ii8** [comment]
I thought about it a bit and came up with #11 
This means that a bignum is not equal to the same number encoded as major type 0 or 1, not sure if that's acceptable.

**Comment by cabo** [comment]
d2ba777 took a slightly different approach: Define map key equivalence at the data model level, and leave most of the types in the generic data model different from each other.
