### ISSUE TITLE
Combine 5.8 and 5.3, new firewall section?

### ISSUE THREAD

**Issue by laurencelundblade** [cbor-wg/CBORbis#122]
Seems like the validity checking discussion is split / duplicated between section 5.8, 5.3 (and security considerations) and combining would be the right thing to do.

Fundamentally, we should insist that all CBOR decoders should behave in a secure way no matter what sort of encoding or serialization or validity is allowed for a CBOR-based protocol. Similarly we should not imply that a CBOR firewall is ever a part of a properly secured CBOR protocol implementation.

We can recommend validity checking as a best practice when designing a CBOR protocol or when implementing a decoder and that it will help with some of the security issues, but it is NOT a substitute for a full properly secure implementation.

We could theoretically say that the requirement of preferred or deterministic encoding in a CBOR-based protocol is a helpful practice for making an implementation more security, but I would prefer not too. The gain seems very small and the misdirection factor seems large. 

Deterministic and valid CBOR share the non-duplication of map keys, but don't share other things like sorting order. I'd prefer that deterministic encoding be focused on the signing use case rather than on any kind of security gains. Validity checking takes care of the duplication of keys, the main security issue.

I think the CBOR firewall discussion should have its own separate section. It could say a really good firewall will do all the validity checks described for all CBOR types AND that no CBOR decoding application should ever rely on a firewall for its security.

**Comment by cabo** [comment]
Once #127 is merged, I'd like to address the editorial part by moving most of the text from 5.8 to 5.3, leaving the first two paragraphs (which probably need some editing, too, along the lines you suggest).

**Comment by paulehoffman** [comment]
#127 has now been merged
