### ISSUE TITLE
Editorial comment about #133

### ISSUE THREAD

**Issue by peteroupc** [cbor-wg/CBORbis#136]
In case you missed it, I made the following comment just as #133 was being merged; it relates to the text added in #133.

> Parts of the paragraph are too close to the one given in, say, http://cbor.schmorp.de/stringref . You should rewrite it in your own words.

**Comment by cabo** [comment]
The reason may be that I suggested some of the wording in that registration...
What do you think needs to be changed?

**Comment by peteroupc** [comment]
I was referring to the text starting with "The decoder needs" and ending with "integrated into the generic encoder/decoder".  But if that text was already your own words, then I see nothing wrong with it.

**Comment by cabo** [comment]
I found the email, dated 2013-11-24 (written from an airport right after the Las Vegas CoAP interop), where I suggested an earlier form of this implementation note.  It is also slightly broken (I blame the airport), so thank you for pointing me to it again.
