### ISSUE TITLE
Add malformed tag example in Appendix G.1.

### ISSUE THREAD

**Issue by fxamacker** [cbor-wg/CBORbis#145]
Tag number should be followed by tag content.  Otherwise, it's not well-formed.

Current line is missing the word "tag":
>A premature end of the input can occur in a head or within the enclosed data, 

Fix it by adding ", tag," like this:
>A premature end of the input can occur in a head, tag, or within the enclosed data, 

Also add malformed tag example to the bullet list of "premature end of the input":
* Tag number not followed by tag content: c0

**Comment by cabo** [comment]
Hi Faye,
the C0 example actually is an example end of input "within the enclosed data", as the tag is a head and a single enclosed data item.  So I don't see a need for the text change.
The example is good, but probably should come with the definite length examples (i.e., be moved two items above).

**Comment by fxamacker** [comment]
Hi Carsten,
I updated the pull request to undo the text change and move tag example to the following position:

> * Definite length maps ...
> * Tag number not followed by tag content: C0
> * Indefinite length strings ...

BTW, I finished reading 7049bis and really appreciate the improvements.  I just added 87 new unit tests to my cbor library based on Appendix G (thankfully they all passed!)  I'm also finding 7049bis  helpful while adding tags support to my generic CBOR library.

**Comment by cabo** [comment]
Thank you for the feedback!  Mind if I forward this to the CBOR mailing list (or maybe you can post there directly)?

**Comment by fxamacker** [comment]
You're welcome!  Please feel free to forward this.  If you prefer I post it there, I'd be happy to do so.

**Comment by fxamacker** [comment]
@cabo Hi Carsten, 
I just emailed cbor@ietf.org for this item.  It's my first post to the mailing list so it might take a while to show up.  I requested adding one-line example to Appendix G.1. and provided URL to my pull request.
