### ISSUE TITLE
"floating point" should be "floating-point"

### ISSUE THREAD

**Issue by laurencelundblade** [cbor-wg/CBORbis#151]
Both are used, "floating-point" is correct.

**Comment by cabo** [comment]
Indeed.  IEEE 754-2019 has the separate-word version only three times, all in references.
Same is true for the current working draft of C++20 (N4842).
ITTF's copy of ISO/IEC 9899 is currently 404 (!), but the working draft I have on my laptop only has about 3 % separate-word versions, and there is no pattern to that, so I'd assume some remaining sloppiness at the draft level as the reason.
There is a little bit of trickery needed as "floating-point" is not a noun, while we used "floating point" as a shortcut for the concept of floating-point representation.  We also used "floating" occasionally as a short-cut noun for "floating-point number".  
Text proposal in PR #157 .
