### ISSUE TITLE
Definition of "preserves its value" and example subnormal float32 inputs for generic CBOR encoders

### ISSUE THREAD

**Issue by x448** [cbor-wg/CBORbis#153]
It would be helpful for 7049bis section 5.5 to state something unambiguous to help generic CBOR encoders produce identical results when using "preferred serialization" or when protocols neglect to specify anything about floating-point numbers:

__EDITED__: removed some ambiguity (oh the irony! :blush:) 
__EDITED__: removed mention of rounding and another item relevant for preservable values
__EDITED__: added NaN
> For generic encoders and floating-point numbers, "preserves its value" means being able to round-trip back to the original floating-point value with all underlying bits unchanged. For example, encode float32 values as float16 only if a round-trip of float32->float16->float32 produces the original float32 with all 32 underlying bits unchanged. This includes 2046 subnormal float32 values that can successfully round-trip in the manner described.  All NaN values must be encoded as 0xf97e00 by default unless the protocol specifies how to encode NaN values (e.g. whether change in signal bit should be ignored when determining if value can be preserved in a smaller size, etc.)

I bring this up because some CBOR encoders avoid converting subnormal float32 values to float16 while other encoders don't avoid them.  Protocols may specify whichever they choose, but  generic CBOR encoders should produce same results when claiming to use "preferred serialization".

These example test values are from my https://github.com/cbor-go/float16 library. Please consider including these values as example float32 inputs along with their corresponding CBOR encoding outputs for generic encoders using "preferred serialization":
```
// float32 subnormal value with coef = 0 and 
// can round-trip float32->float16->float32
f32 = math.Float32frombits(0x38000000) 

// float32 subnormal value with coef !=0 and 
// can round-trip float32->float16->float32
f32 = math.Float32frombits(0x387fc000)

// float32 subnormal value WITHOUT non-zero significand bits dropped and 
// cannot round-trip float32->float16->float32
f32 = math.Float32frombits(0x33c00000) 

// float32 subnormal value WITH non-zero significand bits dropped and
// cannot round-trip float32->float16->float32
f32 = math.Float32frombits(0x38000001)
```

**Comment by x448** [comment]
Removed mention of rounding and one more item in the proposed definition that are not relevant for values that can successfully round-trip as described.  

Add NaN always encoding to 0xf97e00 so definition of "preserves value" doesn't need to deal with special cases like sNaN->qNaN conversions being forced when floating-point values are cast to different size on various languages (sometimes varies by compiler and whether value is const).

**Comment by peteroupc** [comment]
For your information:  See also #94 and the related pull request #134.

**Comment by x448** [comment]
@peteroupc thanks, I found your #94 informative regarding subnormals.

Latest 7049bis says in 4.2.2. Additional Deterministic Encoding Considerations:
>Subnormal numbers (nonzero numbers with the lowest possible exponent of a given IEEE 754 number format) may be flushed to zero outputs or be treated as zero inputs in some floating-point implementations. A protocol’s deterministic encoding may want to exclude them from interchange, interchanging zero instead.

Unless I'm mistaken, that's the only mention of subnormals in 7049bis.

It seems encoders might handle subnormal numbers in at least three ways:
1.  avoid converting to shorter forms of floating-point even if value can round-trip.
2.  encode to shortest form of floating-point like IEEE binary16 when value can round-trip.
3.  always encode to IEEE binary16 zero.

The first way wastes space, especially for float64 subnormals.
The last way prevents subnormal values from providing a cushion for values that would drop to 0.  

The middle way avoids both extremes and has the advantage of handling subnormals and nonsubnormals the same way.

I may be mistaken, but subnormals on iPhone 4 would likely be zero (not subnormal) by the time it reaches the CBOR encoder.  If subnormals got enabled on iPhone 4 by setting the FZ bit in the FPSCR to zero then subnormals are probably desired instead of zero for a reason.

Protocols that choose to lose some precision for subnormals can specify binary16 zero or some other predefined encoding. As a default, it seems simpler and more streamlined to have preferred serialization for floating-point values be the same for subnormals and nonsubnormals.

https://github.com/fxamacker/cbor uses the middle way but it can be changed (or options added) if that wasn't the best choice:
> With ShortestFloat16, each floating-point value (including subnormals) can encode float64 -> float32 -> float16 when values can round-trip. Conversions for infinity and NaN use InfConvert and NaNConvert settings.
