### ISSUE TITLE
Proposed unambiguous defaults for CBOR, including safe defaults to handle duplicate map keys

### ISSUE THREAD

**Issue by x448** [cbor-wg/CBORbis#156]
_Edited on Jan 10, 2020 to say "produce different outputs given the same inputs among different implementations" and updated definitions of 3 default configurations._
_Edited on Jan 11, 2020 to clarify and add additional restrictions to PreferredSafe, and provide ExampleUnsafe protocol that modifies PreferredSafe for their own custom configuration.

7049bis should provide an unambiguous default for each configurable option when a protocol neglects to specify it.  Otherwise, generic CBOR encoders/decoders as well as under-specified protocols will produce different outputs given the same inputs among different implementations.

This proposal does not limit flexibility of CBOR or future protocols using CBOR.  Nothing prevents protocols using CBOR to specify different options. All they have to do is modify an existing configuration and call it anything else they want like "Not Invented Here Config". :smile:

I propose 3 default configurations that: ignore tags and indefinite length items, use fewest bytes for integers, use float16 as shortest form of float, use IEEE 754 default rounding, and encode NaN values as 0xf97e00:

* __PreferredUnsorted__ -- unsorted
* __PreferredSorted__ -- same as PreferredUnsorted, plus sorted bytewise lexicographic. This is like Core Deterministic Encoding with Rule 2 using IEEE 754 default rounding and NaN values encoded as 0xf97e00.
* __PreferredSafe__ -- same as PreferredSorted, plus encoder doesn't produce duplicate map key so the decoder (if configured to do so) can reject maps that have unsorted or duplicate map keys.  Additionally, require map keys to be integer.  Integer map keys are compact (a goal) and also helps avoid security bugs from mixed key types, valid utf8 strings produced by buggy text conversion, floating-point rounding bugs, floating-point unintended sNaN->qNaN conversions, integer and floating-point producing same number, etc.)  Some CBOR libraries are already capable of automatically converting struct field names to CBOR integer map keys.

> The ExampleUnsafe protocol uses CBOR with a custom configuration that modifies PreferredSafe config to allow both integer and floating-point map keys, and handle duplicate map keys by accepting the first one received and ignoring duplicates as if everything is fine.

Different implementations of a protocol or a generic CBOR encoder/decoder should produce identical results given the same inputs when they use PreferredSafe.  If the input doesn't contain duplicate map keys then PreferredSorted should also produce identical results.

If a protocol specifies anything different from these default configurations, then it MUST NOT call it's configuration by the same name.  For example, if a protocol wants to handle duplicate map keys differently, they are free to specify that, but they MUST NOT claim to be using PreferredSafe configuration.

Example:
> The FooBar protocol uses CBOR with a custom configuration that modifies PreferredSafe config to encode all NaN values as the shortest float16 NaN that preserves values with all sNaN becoming qNaN since AMD/Intel F16C does that when casting floats.

To address CBOR tags and indefinite length, adding a prefix or suffix to the above default configuration names could work.  For example:
* PreferredSafeWithTags
* IndefinitePreferredUnsorted
* IndefinitePreferredSortedWithTags and etc.

Updates #63 #153 #155

**Comment by x448** [comment]
I updated PreferredSafe after giving this more thought, especially from a security perspective.

* __PreferredSafe__ 
  * Encode integers using fewest bytes.
  * Encode floating-point values using shortest floating-point form that preserves value.
     * floating-point forms are IEEE binary64, binary32, binary16 (aka float64, float32, and float16).
     * floating-point conversions to smaller sizes must use IEEE 754 default rounding.
     * "preserves value" means a round trip back to original floating-point size have all underlying bits unchanged. E.g. float32->float16->float32 must produce original float32 value with all 32 underlying bits unchanged from the original value.
     * subnormal floating-point values must also be encoded using shortest form of floating-point that preserves value.  E.g. there are 2046 subnormal float32 values that can round-trip successfully.
     * float64->float16 conversions must produce same value as float64->float32->float16.
     * NaN values are encoded as float16 (0xf97e00).
     * positive and negative infinity values are encoded as float16.
  * Sort bytewise lexicographic.
  * __Duplicate map keys are not allowed__.
    * Map keys must be the same type for the same map (implied if integer type is required.)
    * Map keys must be integer type (never floating-point even for zeros or ones, etc.)
    * Map key values (both positive and negative) must be able to fit 64-bit signed integer.
    * __Decoder must reject entire map__ if it contains unsorted or duplicate map key or non-integer key.

Protocols are free to use custom CBOR configurations, for example:
> The ExampleUnsafe protocol uses CBOR with a custom configuration that modifies PreferredSafe config to allow both integer and floating-point map keys, and handle duplicate map keys by accepting the first one received and ignoring duplicates as if everything is fine.

**Comment by cabo** [comment]
Hi Montgomery,

thank you very much for this useful input.
Before I start commenting details, one question:

> floating-point conversions to smaller sizes must use IEEE 754 default rounding.
> "preserves value" means a round trip back to original floating-point size have all underlying bits unchanged. E.g. float32->float16->float32 must produce original float32 value with all 32 underlying bits unchanged from the original value.

Why do we need the first point if we require the second?

**Comment by x448** [comment]
Hi Carsten,

Ideally these two items could be combined if there's agreement about requiring IEEE 754 default rounding when a protocol doesn't explicitly specify different rounding.
1. floating-point conversions to smaller sizes must use IEEE 754 default rounding.
2. "preserves value" means a round trip back to original floating-point size have all underlying bits unchanged. E.g. float32->float16->float32 must produce original float32 value with all 32 underlying bits unchanged from the original value.

If item 1 is left out, then different implementations might use different rounding so their round-trip comparison might produce different results.

If item 2 is left out, then it isn't clear how different implementations might test for "preserves value".  One might use round-trip test while another one bypasses it (e.g. by ignoring subnormal input values) to be able to claim they're the fastest.

In the following example, the "preserves value" test is only 0.29 ns/op using Go on linux_amd64 if a round-trip test is not required.  A round-trip test costs up to 6x-10x more due to a combination of factors in Go such as inlining size limit, inability to inline any calls to assembly funcs, etc.
```
prec := float16.PrecisionFromfloat32(f32)  // only 0.29 ns/op (calling assembly func costs 1.5 ns/op)
if prec == float16.PrecisionExact {
   // We don't need expensive round-trip test. Always convert float32 to float16 here.
} else if prec == float16.PrecisionUnknown {
   // These are subnormals that didn't drop any non-zero significand bits.
   // Only 2046 of these can successfully round-trip float32->float16->float32 while preserving value.
   // Currently, fxamacker/cbor does a round-trip test here so it can shrink 2046 values to float16.
   // What does 7049bis want generic encoders to do here for preferred serialization?
}
```

**Comment by cabo** [comment]
Let me try to restate that question more simply and clearly:
When would an implementation that "preserves the value" be applying "rounding"?

**Comment by x448** [comment]
Oh, I see what you're asking!  Thanks for taking time to clarify your question.   I don't think values that can round-trip back to original floating-point type without any underlying bit changed would be affected by the rounding portion of the conversion function.  
 

I'm sorry. FWIW, specifying rounding got important to me while creating and extracting my conversion functions to a separate library so it could be used outside CBOR.  It was frustrating existing Go functions produced different results and they didn't mention what rounding they were using.  Dealing with silent sNaN -> qNaN when casting floats (and two obscure language bugs related to it) also added to the frustration and made me want to specify everything explicitly about floating-point conversions.

What is your preferred 7049bis definition of "preserves the value"?  
Does the same definition for "preserves the value" apply to all subnormal input values?  
Does the same definition of "preserves the value" apply to NaN values with or without ignoring the sNaN -> qNaN change that can silently happen when various languages cast floating-point values?
