### ISSUE TITLE
Review MIME registration text once more

### ISSUE THREAD

**Issue by cabo** [cbor-wg/CBORbis#161]
... and get rid of the artwork.

**Comment by cabo** [comment]
... and the other artwork regressions following it.

**Comment by cabo** [comment]
Francesca writes: 

```
* Section 9.5
 
Considering the Apps Area Working Group does not exist anymore, should the contact here being updated?
```

Use Change Controller: IESG.  Should an author be identified?  (would at this point be the CBOR WG)

**Comment by fpalombini** [comment]
I think contact: cbo@ietf.org or art@ietf.org would work.
