### ISSUE TITLE
Suggestions for default encoding (tagged & untagged) of uninitialized time values for generic encoders

### ISSUE THREAD

**Issue by x448** [cbor-wg/CBORbis#167]
UPDATED on Feb 14, 2020 to default to using CBOR Null when time tag isn't required and CBOR Undefined if time tag is required.

It would be helpful if 7049bis provided guidance on how to encode tagged and untagged time values that are uninitialized if a CBOR-based protocol doesn't specify fully. 

At least one programming language uses January 1, 0001 00:00:00 to indicate uninitialized time but others don't.  Some programmers use 0 or -1 from Unix epoch, but it's obviously risky.

Here's what I'm recommending for a CBOR library since it provides shortest form and isn't specific to any one programming language like Go.

* CBOR Null = zero-value time when time tags are not explicitly required by protocol.
* CBOR Undefined = zero-value time when time tags are explicitly required by protocol. Undefined without tags indicates an encoding problem as mentioned in 7049bis section 5.7.

7049bis 5.7,
>In some CBOR-based protocols, the simple value (Section 3.3) of Undefined might be used by an encoder as a substitute for a data item with an encoding problem, in order to allow the rest of the enclosing data items to be encoded without harm.

If there's more reasonable default behavior for generic CBOR encoders when CBOR-based protocol or app doesn't fully specify what to do, then please let us know.  Thanks.

**Comment by laurencelundblade** [comment]
Seems like there's two things you might want to say about this (and almost any other value):

1) The value is not given, it is absent. For example something was not measured, the clock was not set or such. In some protocols this would be an error. Other protocols might have a default to fill in. If this was expiration in an X.509 cert, this would be an error. This might be saying "I don't know what size I want".
2) The value is intentionally not specified. This is how I'd say "no expiration" in an X.509 cert.  This might be saying "I will take any size".

Seems useful to be able to distinguish these two.

**Comment by x448** [comment]
@laurencelundblade, thanks for providing more food for thought.  BTW, I updated the issue to add default encoding of undefined time when it is text and also needs to be tagged. If you know of other zero values used that are valid RFC 3339, please let me know.

**Comment by x448** [comment]
Here's what I'm recommending for a CBOR library since it provides shortest form and isn't specific to any one programming language like Go.  I updated issue.

* CBOR Null = zero-value time when time tags are not explicitly required by protocol.
* CBOR Undefined = zero-value time when time tags are explicitly required by protocol. Undefined without tags indicates an encoding problem as mentioned in 7049bis section 5.7.

Maybe this or better guidance can be provided in 7049bis.  Or even just a sentence or two in Section 5.7 to provide a specific example of using CBOR Undefined.

**Comment by laurencelundblade** [comment]
CBOR NULL seems to line up with "value not provided". That seems to be what it means in JSON too. You could use it in different places in a protocol, tagged or not. For example, a protocol might have an array of values and you might want to have one value be absent with out disrupting the number of array values.

CBOR Undef seems OK too, except I don't think there is a JSON equivalent. I'm not sure how serious that is.

**Comment by x448** [comment]
@laurencelundblade, I really appreciate your feedback!  Thanks!

The only reason for CBOR Undef was to indicate an encoding problem if app/protocol specified encoding tag numbers 0 and 1 are required (not optional) but that wasn't possible with undefined time values.

RFC 7049 forbids tag numbers 0 and 1 to have tag content CBOR Null.  

:point_right: If 7049bis allows tag numbers 0 and 1 to have CBOR Null as content, then that would be a very nice improvement that resolves this issue.

Alternatively, maybe 7049bis can mention untagged CBOR Null is a reasonable option even when a protocol specifies tag numbers are required (not optional) for time.  This isn't as intuitive as allowing CBOR Null for tag number 0 and 1 but I'll take either one compared to no guidance.

What do you prefer?  [fxamacker/cbor](https://github.com/fxamacker/cbor) is going to start fuzzing tomorrow after adding CBOR tags and duplicate map key options, so it's not too late change how this is handled.

cc @fxamacker

**Comment by x448** [comment]
I'm just going to recommend encoding to CBOR Null instead of CBOR Undef based on last feedback from laurencelundblade plus this in 7049bis:
>While there is a strong expectation that generic encoders and decoders can represent false, true, and null (undefined is intentionally omitted) in the form appropriate for their programming environment, implementation of the data model extensions created by tags is truly optional and a matter of implementation quality.
