### ISSUE TITLE
Reserved tag value to represent "no tag" in program code?

### ISSUE THREAD

**Issue by ecorm** [cbor-wg/CBORbis#176]
Should there be a reserved tag value to represent "no tag" in program code, such as (2^64 - 1)? My use case is representing a `[value, tag]` pair in code, where tag is optional. A tag is already (up-to) 64-bits, so adding another boolean to the tuple, as in `[value, tag, hasTag]`, takes up even more space.

I'm currently using 2^64 - 1 as an out-of-band value to represent "no tag", but there's currently nothing that guarantees someone else will request that tag value for another purpose.

It's unfortunate that tag value 0 wasn't reserved right from the start to represent "no tag".

**Comment by jimsch** [comment]
Personally I don't really have a great deal of sympathy for this request.  My first reaction is what are you going to do when you have multiple tags in a row but that would not be the normal case so I guess it could be off of the normal code path while this might be on the normal code path.  In that case I would probably say choose a value which is - this is not a tag and if you really need the tag then do a double tag for that special value.

**Comment by ecorm** [comment]
@cabo If the semantics of the "nop" tag is "tag has no effect", then I fail to see how it can be abused. Implementations are already free to ignore tags they don't understand.

@jimsch I was not aware multiple tags could be "stacked" for the same value. This complicates things for constrained platforms, but I suppose they can always set limits to the number of tags per value in their implementation.

**Comment by ecorm** [comment]
If it's not appropriate to include this proposal in the core standard, I can go ahead and make the IANA registry request for a "no-op" tag. I would request a 1+2 byte tag value to avoid the need for implementations to support large integers. I was thinking 2^16-1 = 65535.

**Comment by cabo** [comment]
Actually, we just discussed this in the CBOR virtual interim meeting and the sense of the (virtual) room was that we do want to have this tag number assignment in the document.  65535 also struck me as the right number for this, by the way.

**Comment by ecorm** [comment]
The max integer value is often used as an out-of-band value, so 65535 makes sense for a 16-bit integer. An embedded CBOR implementation may very well choose to use a 16-bit integer to represent a tag, as there's currently only one tag value that wouldn't fit (RAINS message).
