### ISSUE TITLE
rfc7049bis recommends unrecognized tags cause an error

### ISSUE THREAD

**Issue by mcr** [cbor-wg/CBORbis#182]
RFC7049 specified that CBOR tags which were not recognized should be ignored.
RFC7049bis wishes to change this behaviour such that unknown tags would not be ignored, but would at least, be presented to the application for further determination.  This is a change that would render existing CBOR parsers instantly invalid.
The suggestion is that parsers should be in RFC7049 mode by default, and applications that want RFC7049bis behaviour should initialize the parser with an option that enables it [or use a new parser with awareness].  

Applications that want to make use of tags defined in RFC7049bis need to put the parser in RFC7049bis mode. ??

**Comment by cabo** [comment]
Long discussion in https://mailarchive.ietf.org/arch/browse/cbor/?gbt=1&index=S6TmVACm7I6tHrbyDwVvgOikIM8 -- can we close this issue based on that discussion (and the small nit addressed in #187)?

**Comment by mcr** [comment]
Agreed. Works for me.
