### ISSUE TITLE
Explicitly define the CBOR data model

### ISSUE THREAD

**Issue by jyasskin** [cbor-wg/CBORbis#2]
https://cbor-wg.github.io/CBORbis/ mentions the "CBOR data model" several times, but never actually defines it. Would I be right in thinking an item in the CBOR data model is one of:

1. A real number
2. An octet sequence
3. A sequence of Unicode codepoints
4. An array of items
5. A partial function (map) from items to items
6. An integer tag [0, 2^64) paired with an item
7. `False`
8. `True`
9. `Null`
10. `Undefined`
11. A "Simple" integer [0, 19] or [32, 255].

? Would we then want to say that an embedding protocol or implementation can add or remove types of items to the data model, for example to add points in time or remove non-integer real numbers?

**Comment by cabo** [comment]
That is a great idea.
I have written a draft section and put it into `datamodels.md`.
Discussion of this section (and whether we want to have it in the bis document) should occur on the mailing list `cbor@ietf.org`.

**Comment by paulehoffman** [comment]
Included in https://github.com/cbor-wg/CBORbis/pull/8
