### ISSUE TITLE
Diagnostic format should be a surjection onto valid CBOR bytes

### ISSUE THREAD

**Issue by ciphergoth** [cbor-wg/CBORbis#204]
The diagnostic format should have the property that for any sequence of bytes that decodes as valid CBOR, there should be a diagnostic format that maps to it. It very nearly does have this property: for example, encoding indicators give us different representations for `1` -> 01 while `1_0` -> 18 01. As far as I can tell there are only two exceptions, empty indefinite-length byte/text strings and NaN payloads.

Indefinite-length byte strings: currently both 5F FF and 7F FF encode as `(_ )`.

NaN payloads: IEEE 754 permits NaN to carry a [payload](https://montcs.bloomu.edu/Information/LowLevel/IEEE-754.html).  However, currently both F9 7E 00 and F9 7F FF encode simply as `NaN`.

As far as is possible, looking at the diagnostic format should be able to substitute for looking at the bytes directly.  If a piece of software fails only when a non-standard NaN is sent over in CBOR - perhaps it loses the payload and then some checksum fails - then the author will be very sad that the diagnostic format didn't reveal this to them. The format is so close to the goal of being surjective, it seems very desirable to plug these final holes.

**Comment by cabo** [comment]
Indeed, the empty indefinite-length string ambiguity was known (and we would have fixed it if there had been an obvious fix; so this is now about finding a not-so-obvious fix).  
For NaN payloads, it would be interesting to see how other diagnostic formats that involve IEEE 754 floats solve this problem.
I found some discussion explaining why they didn't do that either on http://amzn.github.io/ion-docs/docs/float.html

**Comment by ciphergoth** [comment]
I did some searches but was unable to find previous discussion of the 5FFF/7FFF problem - link me to it? I had in mind something dumb like `(_b )` and `(_b h'dead', h'baad' )` and `(_t "hello ",  "world" )` but perhaps that's already been considered and rejected?

The NaN problem is really ugly, and like you I've been unable to find examples of a float diagnostic format that encodes this information :( `NaN_1_x7E00` and `NaN_1_x7FFF` or something? Seems slightly cleaner to put the whole float in there rather than try to restrict it to just the NaN payload, so we just say that it's an error to use this format for something that's not a NaN eg `NaN_1_x0000` or `NaN_1_x7C00` are invalid, while `NaN_1_x7C01` is valid. Then `NaN` on its own is a synonym for `NaN_1_x7E00` and `NaN_2` for `NaN_1_x7FC00000`.

**Comment by mcr** [comment]
It is probably the case that we can't make a NaN that isn't ugly, but if it has to be ugly, then might as well include the x7E00/x7FFF in there.

**Comment by chrysn** [comment]
One motivation of NAN diagnostic notations was expressing test cases in diagnostic notation. Where this is a use case, expressing noncanonicalities like "integer 0 but encoded with a uint32_t" as well. (Conversely, if that'd go too far, maybe encoding various NANs does too.)

**Comment by ciphergoth** [comment]
I strongly agree that expressing test cases in diagnostic notation is an important application. Diagnostic notation for "integer 0 but encoded with a uint32_t" is `0_2`.

**Comment by cabo** [comment]
I believe we'll need to leave NaN coding as a to-do, but there is a simple solution to the 5fff/7fff problem: ''_ and ""_ — these are slightly ambiguous as ''_ could also be notation for (_ '') or (_ '' '') but we could add a sentence that these are meant to be the empty (no-chunk) indefinite length representation.

**Comment by cabo** [comment]
See also https://mailarchive.ietf.org/arch/msg/cbor/7K5f0rJ-08MTg4C8s8rIwKUldOU/
