### ISSUE TITLE
Terminology Refinement

### ISSUE THREAD

**Issue by BurtHarris** [cbor-wg/CBORbis#25]
To enhance clarity and extensibility in CBORbis, it might be beneficial to adjust some of the terminology and 
definitions used.  For example, instead of the current draft's:

  > Major type 5: a map of pairs of data items. Maps are also called tables, dictionaries, hashes, or objects (in JSON)...   

let's consider saying something less loaded, like:

 > Major type 5/PAIRS - an ordered sequence of zero or more key-value [pairs](https://infra.spec.whatwg.org/#pair)...   

This illustrates a number of shifts in wording and intent which I propose:

* It's simpler and less restrictive.   For example, it does not prevent multimaps from being represented with a properly tagged 5/PAIRS data item.   Multimaps can be quite useful (HTTP and CoAP protocol headers are multimaps), but it is reasonable to limit them as a tagged extension to CBOR (see below.)

* Terms like maps, tables, dictionaries, hashes and objects are .abstract concepts that further restrict allowed content of the 5/PAIRS major type, they are not synonyms for it.   The details of how those abstract types behave is subject to some ambiguity, so it's better not to use them in defining the major type.   CBOR tags can be used to identify which abstract type is intended.  

* CBOR major types should be visually distinct from the abstract types because major type alone does not determine the abstract type of an item; tags can modify the abstract type.  Consistently using both the major type numeric value and an associated name (in caps) would help make the difference clear.

* Saying 5/PAIRS is ordered simply reflects reality, in a CBOR byte stream they _must_ be in some order, because it is a serialization format.   Eliminating the key uniqueness requirement from the major type allows encoding more types, e.g. multi-maps.

However, it would still be desirable to define how an untagged 5/PAIRS acts behave with greater specificity.  For example, to address the issue of key equivalence and canonicalization, it could be very useful for an __UNTAGGED__ 5/PAIRS to adopt the *ECMAScript/JSON object* restrictions that keys be limited to unique numbers and text strings.   Highly constrained environments may have trouble supporting anything more general, but that should not restrict the content of a tagged 5/PAIRS collection, which might allow for the use of a __Map__ tag that could imply full flexibility of encoding non-string/number keys, while a __Map tagged object__ might obey different key-equivalence and canonicalization rules, with greater overhead, for example the byte wise lexicographic order now proposed.

ECMAScript object Canonicalization Order
-----------------------------------------

Modern ECMAScript objects are defined with some little-known behavior that could really help bring to some of the thorny canonicalization issues.   ECMAScript objects are _not_ hashes, their properties _are_ ordered.   But the order can surprise some people, the keys (in order) are:

1. Non-negative numbers keys in ascending order; followed by   

2. Strings keys (including negative numbers) in the order they were added to the object;

3. ECMAScript Symbols (which themselves would have to be tagged in COBAR)

By adopting the above rule as a SHOULD for canonical objects (UNTAGGED 5/PAIRS), we gain several advantages:  

* In CBOR based standards for constrained environments [e.g. CBOR Object Signing and Encryption (COSE)], standardized non-negative integer keys sort first.   A highly constrained implementation of COSE might choose to interpret only the non-negative integer keys in ascending order and skip out when other key types are detected.

* Uniqueness constraints and canonical order of keys made up of other types becomes an application-level concern.   However, applications that handle existing data in a some existing canonical order, should be automatic because the order is preserved.

Most if not all dynamic languages use the ordered map for object properties (rather than unordered) because it can lead to much better performance using JIT compiler technology.   Modern versions of ECMAScript has a separate Map type (since ES2016) with capacity for a wider variety of keys (e.g. objects and arrays can be used as keys), but interestingly it chooses to define equality and uniqueness constraints for map types to be based on reference equality (identity), not value equality.

Mirroring ECMAScript's ordering and uniqueness constraint rules for untagged 5/PAIRS might impose some additional overhead in implementations in other languages, but for the common cases (key isa string and key isa non-negative-integer) it provides a fairly low overhead approach implementable in most (if not all) environments.

Defining the CBOR Data Model in common Web Infrastructure terminology
------------------------------------------------------

I would also like to propose defining the CBOR data model in terms familiar to web developers.   For this purpose, the [WHATWG Infrastructure Living Standard](https://infra.spec.whatwg.org/) includes useful set of [definitons](https://infra.spec.whatwg.org/#index-defined-here) that include most of the concepts needed.  Referencing that document informationally, and selectively copying some of the definitions we need into CBORbis seems appropriate with regard to clarity and intellectual property.   For example, the abstract concepts of the [pair](https://infra.spec.whatwg.org/#pair), [tuple](https://infra.spec.whatwg.org/#tuple), and [struct](https://infra.spec.whatwg.org/#struct) that may be useful for both CBOR and CDDL already exist there.  Furthermore more frequently used terms such as [string](https://infra.spec.whatwg.org/#string) and [byte sequence](https://infra.spec.whatwg.org/#byte-sequence), and the definitions there have been carefully vetted regarding security concerns, for example, excluding surrogate code points in UTF-8.

**Comment by BurtHarris** [comment]
I realize that the semantics I'm proposing above require that a CBOR tag may effect how the serialization of the data value it is attached to.  I trust that's a reasonable assumption, but welcome any concerns.

**Comment by paulehoffman** [comment]
It is quite late for us to change a fundamental term without a strong justification. This document is revising a long-established standard (RFC 7049), and we have not heard that there were any issues with developers in reading RFC 7049.
The ECMAScript canonicalization order is just one way of ordering keys; there are many others in the world. It does not seem prudent to add new restrictions on CBOR to match ECMAScript at this point.
The WHATWG Infrastructure is indeed a living document. It is also far from complete. If someone wants to make a mapping of CBOR to that document, it might be useful to some readers, but delaying this document for it does not seem to buy much for current CBOR users.

**Comment by cabo** [comment]
Thank you, that was good input for discussion.
For what has not been acted upon yet, I agree with Paul that the changes would be too large for a document that is essentially just being stabilized for Internet Standard level.
Asking the WG now whether we can close this.

**Comment by cabo** [comment]
Closing now after interim discussion in the above sense.
