### ISSUE TITLE
Consider expanding the scope of tag 32 to IRIs

### ISSUE THREAD

**Issue by peteroupc** [cbor-wg/CBORbis#34]
Consider expanding the scope of tag 32 to internationalized resource identifiers (IRIs under RFC 3987), not just URIs.  My implementation allows both kinds of identifier under tag 32.

**Comment by cabo** [comment]
I'm closing this issue now; a new tag can easily be defined.

**Comment by peteroupc** [comment]
A CBOR tag relating to IRIs is currently awaiting your review.

**Comment by cabo** [comment]
Thanks -- makes sense!

**Comment by peteroupc** [comment]
For your information, the specification is at: http://peteroupc.github.io/CBOR/iri.html .  Apparently, somehow, the tag number was already taken in the meantime, even though I submitted the request for this number on September 14.
