### ISSUE TITLE
must/may inconsistency on ordering

### ISSUE THREAD

**Issue by laurencelundblade** [cbor-wg/CBORbis#37]
4.7 says 

> Thus, a CBOR-based protocol MUST NOT specify that changing the key/value pair order in a map would change the semantics

The section 4 intro which applies to 4.7 says:

>This section discusses some considerations in creating CBOR-based
   protocols.  It is advisory only and explicitly excludes any language
   from RFC 2119 other than words that could be interpreted as "MAY" in
   the sense of RFC 2119.

My thought would be to move the ordering requirement out of section 4 into section 3. Maybe even a new little subsection. It seems important to make it a clear MUST that the order is not significant.

**Comment by cabo** [comment]
With #17, the solution to the in-your-face contradiction is to remove the promise not to MUST.

3.7 already says "   The CBOR data model for maps does not allow ascribing semantics to
   the order of the key/value pairs in the map representation."  so I think we are covered, except that that paragraph is now slightly broken.  Will fix.

**Comment by cabo** [comment]
Almost closed by #55; rest in #17
