### ISSUE TITLE
No gh-pages branch

### ISSUE THREAD

**Issue by jyasskin** [cbor-wg/CBORbis#40]
Leading to the "editor's draft" link from the https://github.com/cbor-wg/CBORbis/blob/master/README.md to https://cbor-wg.github.io/CBORbis/ being broken.

**Comment by cabo** [comment]
No idea where this branch went -- it certainly still was on my author copy of the repo.  Should be mostly fixed now, but there are some artifacts from the local build I pushed, so I'll wait for the next CI build to succeed to fully close this.

**Comment by jyasskin** [comment]
Looks fixed to me; thanks!
