### ISSUE TITLE
Strict mode can't really be a security solution

### ISSUE THREAD

**Issue by laurencelundblade** [cbor-wg/CBORbis#44]
I do not think it is good to say, or even imply in an IETF standard that a firewall can provide any sort of proper defense against an attacker manipulating data in a protocol. The only proper solutions to that are either signing the data or the end parser doing the checks, and really only signing is a proper solution. 

I also think the text is problematic because it assumes an attacker can add data, but not modify data, so it only describes defenses against adding data.

The remedy in the text to me would be to remove the discussion of an attacker, or just mention it as one motivation with a caveat that strict mode doesn't actually provide any strong defense.

**Comment by paulehoffman** [comment]
The term "gatekeeper function" should also be removed.

**Comment by paulehoffman** [comment]
Fixed by #49
