### ISSUE TITLE
Try for two levels of decoding error?

### ISSUE THREAD

**Issue by laurencelundblade** [cbor-wg/CBORbis#45]
Seems to me there are two levels of decoding errors. The first is non-well-formed CBOR and is captured in Appendix C and the "Syntax Errors" section. Every CBOR decoder needs deal with these errors. 

The second, is "invalid" CBOR that is detected by a strict mode decoder. It is described in various places with the mention of invalid, the section on "other decoding errors" and the "strict mode" section. It is more open-ended and much more difficult to implement because it can need a lot of RAM and processing power in some cases.  Some decoders may do part of it, but not all of it and that is OK. Some strict mode decoders may do a lot more than others. What is "Invalid CBOR" is thus subjective or at least will vary by implementation.

What I'm after here is a clear characterization of the two levels of decoding error, that a strict mode decoder is one that does more than checking for non-well-formed CBOR, and that strict mode decoders are allowed to be highly variable in what the check.

**Comment by laurencelundblade** [comment]
discussion waiting for pull request #17 and #18

**Comment by cabo** [comment]
Essentially, we now have three levels:

* well-formed (vs. syntactic error).  Not well-formed is now MUST NOT generate/accept.
* valid (vs. semantic error).  Protocol encoders now MUST generate valid CBOR.
* expected (vs. unexpected by application).  This is application-specific and often expressed in CDDL.

I'm not sure we have all in order for strict mode, so I'll leave this open for now, but I think we have nailed the levels.

**Comment by laurencelundblade** [comment]
The three levels make sense to me.

I probably have some comments about invalid / strict mode in the latest merge, but they are not fully formed yet.

**Comment by laurencelundblade** [comment]
See https://github.com/cbor-wg/CBORbis/issues/90

**Comment by cabo** [comment]
This should now be addressed, once #116 merges.  Please check and close if that is correct.

**Comment by cabo** [comment]
This should now be covered.  Can we close this?
