### ISSUE TITLE
two-byte encodings of true, false... should be considered not-well-formed

### ISSUE THREAD

**Issue by laurencelundblade** [cbor-wg/CBORbis#51]
We have this text:
> An encoder MUST NOT encode False as the two-byte sequence of 0xf814, MUST NOT encode True as the two-byte sequence of 0xf815, MUST NOT encode Null as the two-byte sequence of 0xf816, and MUST NOT encode Undefined value as the two-byte sequence of 0xf817. A decoder MUST treat these two-byte sequences as an error. Similar prohibitions apply to the unassigned simple values as well.

Seems like we should adjust the text above and call this "not-well-formed".

We should also fix the code in appendix C to catch this error especially as appendix C says "The data is well-formed if and only if..."

**Comment by jyasskin** [comment]
#17 does call this "not well-formed", but it doesn't adjust appendix C. I agree the appendix C code should do this, but would like to avoid expanding #17 more.
