### ISSUE TITLE
Rules about handling identical map keys

### ISSUE THREAD

**Issue by jyasskin** [cbor-wg/CBORbis#63]
In https://cbor-wg.github.io/CBORbis/draft-ietf-cbor-7049bis.html#map-keys, we say,

> A CBOR-based protocol should make an intentional decision about what to do when a receiving application does see multiple identical keys in a map. The resulting rule in the protocol MUST respect the CBOR data model: it cannot prescribe a specific handling of the entries with the identical keys, except that it might have a rule that having identical keys in a map indicates a malformed map and that the decoder has to stop with an error.

I'm not sure what decisions are open to a protocol following this advice. I'd like protocols to decide between choices like:

1. Error. (Preferred, but I can't always get what I want. 😃)
2. Take the first of several identical keys and ignore later ones.
3. Take the last of several identical keys and ignore earlier ones.

I'd prefer to exclude protocols that specify something like "concatenate the arrays contained in the values for identical keys".

However, if the protocol "cannot prescribe a specific handling of the entries with the identical keys", it seems like it can't say to "take the first one and ignore later ones". Is there some other wording that better expresses what we mean here?

**Comment by cabo** [comment]
The existence of Rules 2 and 3 together creates two mutually incompatible CBOR universes.  We need to avoid this.  That's why it says "it cannot prescribe a specific handling of the entries with the identical keys".  A "strict" decoder would perform some checking, but that would be limited to the generic data model; the application might then have to re-check in its application data model.  All the application can request from a generic decoder here is being "strict" vs. leaving the handling of dups open to the decoder.

**Comment by jyasskin** [comment]
This section is about protocol-specific decoders, not generic decoders. What behaviors are available to the protocol's decoder other than "error"? I'm worried that "let different decoders behave differently" is a recipe for security bugs, and it's not an "intentional decision" anyway. I'd be fine saying that protocol decoders MUST error on duplicate keys, but if that's what we mean, we should say it more directly.

**Comment by cabo** [comment]
I do not believe that all decoders must be validating, but that would be a prerequisite to a must error on duplicate.  A typical generic decoder will simply discard duplicates, so the application would not see them.  So, theoretically, I understand what you are trying to achieve, but I would not want to burden the ecosystem with the need to always validate against duplicate keys.

**Comment by jyasskin** [comment]
Per IETF 106 discussion, I started a mailing list thread at https://mailarchive.ietf.org/arch/msg/cbor/hQDMXnvoAZZK-HQh40oqc48XR2k.
