### ISSUE TITLE
Consider splitting "data item" from "encoded data item"

### ISSUE THREAD

**Issue by jyasskin** [cbor-wg/CBORbis#64]
In https://cbor-wg.github.io/CBORbis/draft-ietf-cbor-7049bis.html#terminology, we define "data item" as

> ... The term is used both for the data item in representation format and for the abstract idea that can be derived from that by a decoder.

However, in https://cbor-wg.github.io/CBORbis/draft-ietf-cbor-7049bis.html#encoding, we've started using "encoded data item" to distinguish the "representation format" from the "abstract idea". Would it make sense to split the terms in the Terminology section too?

**Comment by cabo** [comment]
Too bad that Chrome does not have "view-lossage", must have pressed some key combo...

A lame PR for this is #129 

(We have four instances of "encoded data item" in master right now.  A better term would be nice, but doesn't come up easily.)
