### ISSUE TITLE
Tags that have been assigned since the initial assignments

### ISSUE THREAD

**Issue by jyasskin** [cbor-wg/CBORbis#65]
https://cbor-wg.github.io/CBORbis/draft-ietf-cbor-7049bis.html#tags says,

> Table 3 provides a list of initial values, with definitions in the rest of this section.

The table itself contains entries like 

> 6..20 | (Unassigned) | (Unassigned)

except RFC8152 assigned 16..18. It might be more accurate for the bis spec to say "Not assigned by this specification" or similar?

**Comment by cabo** [comment]
Covered by #84.
