### ISSUE TITLE
Advise/require protocols to specify how they handle unknown tags/simple values

### ISSUE THREAD

**Issue by jyasskin** [cbor-wg/CBORbis#67]
https://cbor-wg.github.io/CBORbis/draft-ietf-cbor-7049bis.html#unknown-tags says

> A decoder that comes across a tag (Section 3.4) that it does not recognize, … , might …, might …, might …, or take some other type of action.

The protocol definition should specify which of those happens.

We already have:

> CBOR-based protocols MUST specify how their decoders handle invalid and other unexpected data.

and since an unknown tag or simple value is certainly unexpected, that obliquely requires the protocol to specify its behavior on unknown tags and simple values, but we shouldn't require folks to read the spec that carefully. 

I think we could just remove this section, but if you think laying out the options is valuable, I'd suggest we add them after

> CBOR-based protocols MUST specify how their decoders handle invalid and other unexpected data.

with "For example" and then start a new paragraph before

> CBOR-based protocols MAY specify

**Comment by cabo** [comment]
(Waiting for #127 to merge)

**Comment by paulehoffman** [comment]
#127 has been merged.

**Comment by cabo** [comment]
In #131 I opted for your simple solution -- removing the (now redundant and less specific than existing) text.  But maybe you have the same reservations against the edited text in 5.3/5.4?
