### ISSUE TITLE
Describe valid / invalid for every type 

### ISSUE THREAD

**Issue by laurencelundblade** [cbor-wg/CBORbis#71]
The document should probably explicitly document every case of invalid CBOR for the data types in the document.  Most of these are the tags. Probably many of them can be handed by saying "Encoded CBOR with this tag that doesn't conform to this description is invalid".

I think the only two cases of invalid CBOR for the major types are.
 - Bad UTF-8 for Major type 3
 - Duplicate keys for Major type 5

**Comment by jimsch** [comment]
Incorrect number of items for indefinite maps.  The 0xff is in the wrong place.

**Comment by paulehoffman** [comment]
I am seeing all of these (other than the tags) as already saying that they are invalid or at least bad. Are you asking for a separate section that lists invalid CBOR, or some better marker in the text?

**Comment by laurencelundblade** [comment]
I was asking for some sentences for each tag that describes what is valid for that tag. For example, for the B64 tag it says that the major data type must be tstr and that it only contains valid B64 characters or it is invalid. In the case of something like MIME, it would have to say non-compliance with the MIME spec makes the CBOR invalid. This might be a bit of a slippery slope.

To me well-formed or not is something all generic CBOR decoders must discriminate. They must error out on non-well-formed.  

Whether a generic decoder errors out on invalid / valid is optional and dependent on the decoder and its features. Very often determination of invalid / valid is expensive and awkward for the generic CBOR decoder but easy and natural for the next layer in the protocol stack. For example it awkward and even wasteful for a generic CBOR decoder to fully check B64 or MIME formatting while a B64 or MIME decoder must intrinsically do these check no matter what.

**Comment by laurencelundblade** [comment]
To comment on Jim's comment from some time ago -- both of those should be non-well-formed. They are easily detectable by generic decoders.   

I have filed #80 for an uneven number of items in a map.

**Comment by cabo** [comment]
These all should be covered now.  Can we close this?
