### ISSUE TITLE
Specify a default JSON-to-CBOR conversion of numbers for canonicalization purposes

### ISSUE THREAD

**Issue by peteroupc** [cbor-wg/CBORbis#77]
The section "Converting from JSON to CBOR" currently says:

> JSON numbers without fractional parts (integer numbers) ...; integers longer than _an implementation-defined threshold_ (which is usually either 32 or 64 bits) may instead be represented as floating-point values. 

Currently, the W3C Recommendation "Web Authentication" incorporates this section (section 4.2 in the RFC) by reference in the algorithm to _canonicalize_ CBOR from JSON.  Because this section specifies "an implementation-defined threshold", and Web Authentication doesn't specify a default threshold, two different implementations can _theoretically_ produce different "canonical" versions of the same JavaScript object depending on whether they encode a particular high-valued integer number as a CBOR integer or as a CBOR floating-point number.  (If it weren't for canonicalization, such implementation differences would matter much less.)  See also [this issue](https://github.com/w3c/webauthn/issues/1044).

Thus, I suggest that the section "Converting from JSON to CBOR" include a default threshold (e.g., 2^31, 2^53, or some other threshold, preferably one followed by the majority of implementations) for encoding integer numbers from JSON to CBOR in case a protocol incorporates this section by reference without giving a default value for this threshold.

**Comment by peteroupc** [comment]
The WebAuthn issue was just closed with no action taken.  For the sake of WebAuthn and other protocols like it, the CBOR specification should include a default threshold for encoding integer numbers from JSON to CBOR to avoid divergence of implementations that decide differently on this detail.

**Comment by cabo** [comment]
I believe the default threshold should be 2**53 (exclusive).  There may be a need for a distinction between I-JSON-based converters and pure-JSON-based ones (which would not need such a threshold, instead they would go to bignums if needed).

**Comment by peteroupc** [comment]
I have edited the title because, for canonicalization purposes, the following defaults need to be specified for JSON-to-CBOR conversion of numbers in case a protocol using canonical CBOR from JSON incorporates the CBOR RFC by reference:

- The _default_ threshold below which integer numbers are encoded as CBOR integers rather than as a floating-point number.  (Note that until recently, the only number type in JavaScript is `Number`, which is a 64-bit _floating-point_ number.)
- Whether, _by default_, floating-point numbers are encoded using their shortest CBOR encoding or always using the 64-bit encoding form.
- The _default_ limit of the precision of floating-point numbers (e.g., 64-bit floating-point numbers).

In addition, this issue also affects the FIDO Client-to-Authenticator Protocol version 2 (see [section 6](https://fidoalliance.org/specs/fido-v2.0-id-20180227/fido-client-to-authenticator-protocol-v2.0-id-20180227.html#message-encoding)).
