### ISSUE TITLE
“foregoing” in BSON section should be “forgoing”

### ISSUE THREAD

**Issue by FGasper** [cbor-wg/CBORbis#79]
From what I can see, to “forego” is to go before. To “forgo” is to do without, which seems to be the intended meaning here.

**Comment by cabo** [comment]
Interesting.  My dictionary has forego as a variant spelling of forgo.  But it forgo is the primary spelling, we should go for (!) that.

**Comment by paulehoffman** [comment]
My _Oxford American Dictionary_ has "foregoing" as "preceding, previously mentioned", so the current spelling is correct.

**Comment by FGasper** [comment]
@paulehoffman That makes no sense. The intended meaning is clearly “to do without”, not “preceding”.

**Comment by FGasper** [comment]
> Its major distinguishing feature is the capability for in-place update, foregoing a compact representation.

**Comment by FGasper** [comment]
i.e., BSON gives up (“does without”) a compact representation in exchange for its distinguishging ability to update in-place.

**Comment by paulehoffman** [comment]
Yeeps, I totally misread that. You are correct. Fixed by #88.
