### ISSUE TITLE
Tag validity: Need more text

### ISSUE THREAD

**Issue by cabo** [cbor-wg/CBORbis#86]
We need text that explains the structural tag validity approach used in CBORbis and 7049, and a potential semantic tag validity approach.

We also need to explain our rationale for some of the validity decisions (e.g., why do we check embedded MIME but not embedded CBOR?  That may be a bug on its own.)

**Comment by cabo** [comment]
Suggestion from the 2019-07-03 interim: The CBOR must be well-formed for the tag to be valid.
(The MIME reference would be a downref?)  Conformance would be to RFC 2049.

**Comment by paulehoffman** [comment]
Nudge to @cabo: Did we address this fully yet?

**Comment by cabo** [comment]
We addressed the issue about the two specific tags, but not yet the full "semantic tags" question.  Inching closer with  #131, will revisit this soon.

**Comment by cabo** [comment]
We are getting asymptotically close -- we could spend a lot more time on this, but with diminishing returns.  Closing now -- but might be good to check in the WGLC whether we all agree on this.
