### ISSUE TITLE
Tags that care about their relative order in a CBOR document

### ISSUE THREAD

**Issue by peteroupc** [cbor-wg/CBORbis#92]
The IANA registry contains several tags that serve as references to previously seen items in a CBOR document in a way that their relative order in the document is important unlike for most other CBOR tags.

- [Tag 25](http://cbor.schmorp.de/stringref) is a reference to a previously seen string in (part of) a CBOR document.
- [Tag 29](http://cbor.schmorp.de/value-sharing) is a reference to a previously seen shareable object in a CBOR document.

Because tagged objects can be presented in a different order by a CBOR implementation if they appear in a CBOR map (because such an implementation may present map keys in an unspecified order), **I think the CBOR specification should discourage future definitions of tags that care about their relative order** as tags 25 and 29 do, as they can't be implemented on top of a CBOR implementation that uses the generic CBOR data model. 

An example of this problem is shown for tag 29 (which works with tag 28 which marks sharable objects).

Suppose a CBOR document has the following form:

    {"k1": 28("v1"), "k2": 28("v2"), "k3": 29(0), "k4": 29(1)}

The document above could expand to the following:

    {"k1": "v1", "k2": "v2", "k3": "v1", "k4": "v2"}

However, if a generic CBOR implementation lists the map's keys in the following order: `"k4"`, `"k2"`, `"k3"`, `"k1"` (which could happen if the implementation uses hash tables to represent maps), then it would internally store the CBOR document as:

    {"k4": 29(1), "k2": 28("v2"), "k3": 29(0), "k1": 28("v1")}

Which could only be expanded, at best, to:

    {"k4": 29(1), "k2": "v2", "k3": "v2", "k1": "v1"}

This is why the CBOR specification should discourage tags serving as references of the kind I just mentioned.  Note that this discussion does not apply to tags&mdash;

- that mark references outside the CBOR document (such as URIs or the draft CoRAL's dictionary references), or
- that mark references within the CBOR document that are insensitive to order (such as marking those references with strings similar to HTML `id` attributes),

since in both cases, a higher-level application could easily fix up those references, even within CBOR maps, regardless of the order in which the CBOR decoder presents map keys.

**Comment by cabo** [comment]
Hi Peter,

thank you for pointing this out.  The tags were defined early in the life of CBOR for use in a specific language ecosystem. The tags in question clearly document the anomaly -- these tags can only be used if tag processing is integrated with decoding.

When we address tag validity, we may wish to add a note that tags can't rely on map ordering, just like we have one that says applications cannot rely on map ordering.

We also should define a compression scheme that operates at the data model level; we discussed one of these a couple of year ago in a WG meeting and can go ahead once we have the rechartering and one or more drafts to choose from.

**Comment by paulehoffman** [comment]
A nudge to @cabo : Have we dealt with this fully yet?
