### ISSUE TITLE
Signaling NaN and subnormal numbers

### ISSUE THREAD

**Issue by peteroupc** [cbor-wg/CBORbis#94]
### Signaling NaN

CBOR's floating point support (head bytes 0xf9-0xfb) makes it possible to store what are treated as signaling NaNs in x86, x64, and other popular instruction set architectures.  A _signaling NaN_ is an NaN in which the highest bit of the mantissa area is clear (as opposed to a _quiet NaN_, in which that bit is set). Most of these architectures can only output quiet NaNs, not signaling NaNs, and when they receive a signaling NaN, they can trigger a floating-point exception and/or convert the signaling NaN to a quiet NaN (by setting the mantissa area's most significant bit).  This makes signaling NaNs generally problematic to store in any serialization format, including CBOR.  

The NaN issue is already covered to some degree in the deterministic encoding section (especially the suggestion to choose one NaN form for deterministic encodings).  However, there are several other things worth mentioning:

- In some programming environments (including .NET, it seems), it might not be possible to create a signaling NaN in software; thus, for example, a .NET application that encounters a CBOR-encoded quiet NaN and a CBOR-encoded signaling NaN might decode both as quiet NaN; this makes it problematic for an application that rejects CBOR not in a deterministic encoding, since it would accept both CBOR encodings even though the quiet NaN encoding is preferred.
    - One solution: For deterministic encoding purposes, a CBOR decoder can check the bytes of the CBOR-encoded floating-point value; if the value resolves to a NaN (either by inspecting the bytes directly or by using an appropriate method, e.g., `Double.IsNaN()` in .NET or `Number.isNaN()` in JavaScript), check whether the bytes correspond to the preferred encoding of NaN.
- If a signaling NaN is converted in software to a smaller format (e.g., 64-bit to 16-bit floating values), it is possible that the bits that are discarded in the process can turn the NaN into an infinity instead (which has a mantissa area of 0).  It then becomes an issue to decide how to turn such a value back into an NaN (either by making it a quiet NaN or introducing some other bit into the mantissa area).  However, this issue occurs only if an application always generates only the 32-bit or only the 16-bit CBOR encoding for floating-point values.
- If an application has set up floating-point exception handlers, those exceptions may be triggered, even unwittingly, if the application decodes a CBOR-encoded signaling NaN.  Since not many programming environments enable the use of custom exception handlers of this kind, however, this issue seems not to occur often in practice; still, this is an issue to keep in mind.

### Subnormal Numbers

A _subnormal number_ is a nonzero number with the lowest possible exponent of a given IEEE 754 number format.  Because subnormal numbers are complicated to support compared with other numbers, some instruction set architectures support modes that treat subnormal inputs and/or outputs as zero, and these modes may be enabled by default (e.g., [in iPhone 4](https://stackoverflow.com/questions/7346521/subnormal-ieee-754-floating-point-numbers-support-on-ios-arm-devices-iphone-4) and possibly other mobile devices).  Examples of these modes are the _flush-to-zero_ mode in certain ARM processors, as well as the [FTZ and DAZ modes](http://software.intel.com/en-us/articles/x87-and-sse-floating-point-assists-in-ia-32-flush-to-zero-ftz-and-denormals-are-zero-daz/) in the IA-32 instruction set architecture.

Because of this, subnormal numbers are likewise problematic to store in any binary serialization format, including CBOR, and are an important thing to consider for any protocol that wishes to support floating-point numbers, especially for deterministic encoding purposes.

**Comment by cabo** [comment]
I still need to spend some quality time with IEEE754:2019 (yes, an update just came out); there is some new text about NaNs and NaN payloads there.  Generally, converting into a smaller format can only lose precision (and thus the distinction between an sNaN and Infinity) when allowed by the application.  CBOR currently does not say anything useful about NaN payloads (and pretty much rules them out for deterministic encoding).  This does require some more thinking.
