### ISSUE TITLE
Negative zero

### ISSUE THREAD

**Issue by peteroupc** [cbor-wg/CBORbis#95]
The CBOR data model distinguishes floating-point negative zero from floating-point positive zero. For most but not all purposes in applications, both kinds of zero are the same.

Perhaps mention that a protocol that uses deterministic encoding and supports floating-point numbers ought to specify how to handle negative zero; e.g., by requiring the distinction to be preserved, by requiring negative zero to be encoded as positive zero, by disallowing negative zero, or otherwise.

The negative zero issue could also be mentioned somehow in section 5.5.

**Comment by cabo** [comment]
#102 adds a sentence in 4.2.2.  Not sure what needs to be added in 5.5.  Please check.

**Comment by paulehoffman** [comment]
Closing this because Peter commented in PR for it, so I'm assuming he liked the change. If not, please re-open the PR.
