### ISSUE TITLE
well-formed pseudo code bug with indefinite length strings

### ISSUE THREAD

**Issue by laurencelundblade** [cbor-wg/CBORbis#96]
The pseudo code does not catch an indefinite length string inside an indefinite length string.  Here's an example:

```
5f 5f 41 00 ff ff 
```

This is called out as not-well-formed

> If any item between the indefinite-length string indicator (0b010_11111 or 0b011_11111) and the "break" stop code is not a definite-length string item of the same major type, the string is not well-formed.

In the code below if (it != mt) is not enough of a check. It needs to see that the argument is not 31

```
well_formed_indefinite(mt, breakable) {
  switch (mt) {
    case 2: case 3:
      while ((it = well_formed(true)) != -1)
        if (it != mt)           // need finite embedded
          fail();               //    of same type
      break;
    case 4: while (well_formed(true) != -1); break;
    case 5: while (well_formed(true) != -1) well_formed(); break;
    case 7:
      if (breakable)
        return -1;              // signal break out
      else fail();              // no enclosing indefinite
    default: fail();            // wrong mt
  }
  return 0;                     // no break out
}
```

**Comment by cabo** [comment]
On Jul 29, 2019, at 20:34, Laurence Lundblade <notifications@github.com> wrote:
> 
> In the code below if (it != mt) is not enough of a check.

It is always a bit hard to test pseudo-code, but why do you think that the nested call to well_formed will return 2 for 0xf5f540ffff?

Grüße, Carsten

**Comment by laurencelundblade** [comment]
cbor.me and your Ruby code have the problem. I have tested against both of those. My decoder has the problem too.

I see no check in the recursion through well_formed() and well_formed_indefinite() to catch this. My guess at a fix would be to pass the ai (the argument) to well_formed_indefinite() and check that it is not 31 for case 2 and 3.

**Comment by cabo** [comment]
On Jul 29, 2019, at 21:31, Laurence Lundblade <notifications@github.com> wrote:
> 
> cbor.me and your Ruby code have the problem. I have tested against both of those. My decoder has the problem too.

I don’t doubt that.

> I see no check in the recursion through well_formed() and well_formed_indefinite() to catch this. My guess at a fix would be to pass the ai (the argument) to well_formed_indefinite() and check that it is not 31 for case 2 and 3.

Please see the specific question in my previous comment.
I wrote a quick test harness for the pseudo code and it works for me.

Grüße, Carsten

**Comment by laurencelundblade** [comment]
I think there might be a problem because:

- when I execute the code in my head (and a scratch pad) it looks like it fails
- I see no check for ai == 31 when when checking the indefinite string chunks and one seems necessary. My code needed it.

I certainly could be missing something, but that seems enough evidence to file an issue.  Maybe better to trust the running code. :-)

**Comment by cabo** [comment]
When I run it on 0xf5f5ffff (or 0x5f5f4100ffff) it indeed fails, which is the correct behavior.

The `ai==31` check is at the start of `well_formed`, where `well_formed_indefinite` is called for indefinite length items, which returns 0 or -1; the actual mt is only returned for definite length (see comment there).  Within `well_formed_indefinite` case 2 and 3, the return of the embedded well_formed is checked for `it == mt`, which can only be true for definite length enclosed items (indefinites return 0); see the comment on that check.

**Comment by cabo** [comment]
#101 adds a note to the pseudocode appendix to explain this better.  Please review.

**Comment by cabo** [comment]
I think we can close this now.
