### ISSUE TITLE
Empty indefinite-length data items

### ISSUE THREAD

**Issue by peteroupc** [cbor-wg/CBORbis#97]
Clarify that indefinite-length items with nothing inside are allowed, and are treated as empty data items (empty text strings, byte strings, arrays, and maps).  In other words, clarify that the following byte sequences are well-formed: 0x5f.ff, 0x7f.ff, 0x9f.ff, 0xbf.ff .  This clarification is consistent with the streaming use case mentioned in the document, since an encoder (in a streaming context) could then write an indefinite-length start byte (0x5f, 0x7f, 0x9f, 0xbf) without having to know _whether_ any data for that major type follows.

**Comment by cabo** [comment]
Indeed, the “zero or more” wording from the start of 2.2.2 in RFC 7049 was lost in the edits that led to 3.2.3 in 7049bis.  Something like this needs to be reinstated.  (I’m less sure of the need for a clarification for 3.2.2, but using a “zero or more” formulation cannot really hurt there, either.)

Thank you!

Grüße, Carsten
