### ISSUE TITLE
Security considerations for decimal fractions and bigfloats with extremely large or extremely small exponents

### ISSUE THREAD

**Issue by peteroupc** [cbor-wg/CBORbis#98]
Decimal fractions and bigfloats (tags 4 and 5) allow encoding numbers with exponents that are extremely large (tens of thousands or more) or extremely small (negative tens of thousands or less), so large to be unreasonable for most applications.

I have just added security considerations to my [tag pages for extended numbers](https://peteroupc.github.io/CBOR/extended.html) that explain security issues with such numbers in detail; they also apply to tags 4 and 5 since they allow exponents as high as 2^64 - 1 and as low as -(2^64).

**Comment by cabo** [comment]
#99 contains a minimal change.  Your considerations add considerable detail to the implementation advice, but maybe go a bit further than we need.  Please discuss.

**Comment by peteroupc** [comment]
Certain operations on arbitrary-precision numbers, such as comparison, addition, and conversion to a bignum, vary greatly in their running time, by orders of magnitude.  A denial-of-service risk occurs, for example, if a CBOR map's keys include decimal fractions and bigfloats that take an extremely long time to compare numerically with each other (as opposed to a byte-by-byte comparison) -- an example is comparing 800e1000000 with 800p3200000 (there may be better examples).

By the way:

- Section 10 doesn't seem to cover denial of service risks in general.  For example, an implementation can receive a CBOR map intentionally designed to trigger hash table collisions (e.g., "Hash-flooding DoS reloaded: attacks and defenses", CCC 2012).  Protocols can mitigate this by requiring a deterministic encoding; one example is found in the FIDO Client-to-Authenticator Protocol 2.
- Section 10 should replace "a TLS-secured channel" to "a secure communication channel", since readers may not be familiar with TLS (Transport Layer Security) and to broaden its scope.

**Comment by cabo** [comment]
Actually, the text should probably also cover other processing required by Tags beyond those in the base spec.
